version: "3.9"

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831"
      - "16686:16686"
  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
