// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/weegigs/wee-events-go"
	"github.com/weegigs/wee-events-go/dynamo"
	"github.com/weegigs/wee-events-go/samples/counter"
)

// Injectors from wire.go:

func live(ctx context.Context) (we.EntityService[counter.Counter], func(), error) {
	v := counter.PseudoRandomizer()
	config, err := dynamo.DefaultAWSConfig(ctx)
	if err != nil {
		return nil, nil, err
	}
	client := dynamo.Client(config)
	eventStoreTableName, err := dynamo.LiveEventsTableName()
	if err != nil {
		return nil, nil, err
	}
	jsonEventMarshaller := we.NewJsonEventMarshaller()
	dynamoEventStore := dynamo.NewEventStore(client, eventStoreTableName, jsonEventMarshaller)
	entityService := counter.CreateCounterService(v, dynamoEventStore)
	return entityService, func() {
	}, nil
}

func local(ctx context.Context) (we.EntityService[counter.Counter], func(), error) {
	v := counter.PseudoRandomizer()
	dynamoEventStore, err := dynamo.LocalDynamoStore(ctx)
	if err != nil {
		return nil, nil, err
	}
	entityService := counter.CreateCounterService(v, dynamoEventStore)
	return entityService, func() {
	}, nil
}
