// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/weegigs/wee-events-go"
	"github.com/weegigs/wee-events-go/dynamo"
	"github.com/weegigs/wee-events-go/samples/counter"
	"github.com/weegigs/wee-events-go/support"
)

// Injectors from dynamo-controller.go:

func DynamoCounterService(ctx context.Context, tableName dynamo.EventsTableName, randomize func() int) (we.EntityService[counter.Counter], error) {
	config, err := support.AWSConfig(ctx)
	if err != nil {
		return nil, err
	}
	client := dynamo.Client(config)
	jsonEventEncoder := we.NewJsonEventEncoder()
	dynamoEventStore := dynamo.NewEventStore(client, tableName, jsonEventEncoder)
	entityService := counter.CreateCounterService(randomize, dynamoEventStore)
	return entityService, nil
}
