// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/weegigs/wee-events-go/samples/counter"
	"github.com/weegigs/wee-events-go/stores/ds"
)

// Injectors from wire.go:

func live(ctx context.Context) (CounterService, func(), error) {
	config, err := ds.DefaultAWSConfig(ctx)
	if err != nil {
		return nil, nil, err
	}
	client := ds.Client(config)
	eventStoreTableName, err := ds.EventsTableNameFromEnvironment()
	if err != nil {
		return nil, nil, err
	}
	encoder := jsonEncoder()
	dynamoEventStore, err := ds.NewEventStore(client, eventStoreTableName, encoder)
	if err != nil {
		return nil, nil, err
	}
	v := counter.PseudoRandomizer()
	v2 := NewCounterService(dynamoEventStore, v)
	return v2, func() {
	}, nil
}

func local(ctx context.Context) (CounterService, func(), error) {
	encoder := jsonEncoder()
	dynamoEventStore, err := ds.LocalDynamoStore(ctx, encoder)
	if err != nil {
		return nil, nil, err
	}
	v := counter.PseudoRandomizer()
	v2 := NewCounterService(dynamoEventStore, v)
	return v2, func() {
	}, nil
}
