// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/weegigs/wee-events-go/samples/counter"
	"github.com/weegigs/wee-events-go/stores/ds"
)

// Injectors from dependencies.go:

func live(ctx context.Context) (GatewayHandler, func(), error) {
	config, err := ds.DefaultAWSConfig(ctx)
	if err != nil {
		return nil, nil, err
	}
	client := ds.Client(config)
	eventStoreTableName, err := ds.EventsTableNameFromEnvironment()
	if err != nil {
		return nil, nil, err
	}
	dynamoEventStore := ds.NewEventStore(client, eventStoreTableName)
	entityLoader := counter.Loader(dynamoEventStore)
	v := createHandler(entityLoader)
	return v, func() {
	}, nil
}
